Test for fr env / APP_SECRETS before running commands
fortrabbit/craft-copy pull request #119
Opened 2021-07-08 13:05 UTC by tomdavies

fixes #87

2021-07-15 15:59 UTC, ostark requested changes
getenv() returns something falsy if the var is not set.

2021-07-15 15:59 UTC, ostark commented on src/Actions/StageAwareBaseAction.php
> +        return getenv('APP_SECRETS') && getenv('APP_SECRETS') == '/etc/secrets.json';
the first `getenv()` is not needed.

2021-09-02 16:19 UTC, tomdavies commented
@ostark done

2023-01-23 12:39 UTC, frank-laemmer commented
https://github.com/fortrabbit/craft-copy/issues/87

2023-01-27 10:35 UTC, ostark commented
Replaced by https://github.com/fortrabbit/craft-copy/pull/156 for no reason (copy&paste was easier than resolving git conflicts)

2023-01-27 10:35 UTC, closed without merging